Update Chained Exception test from #965
spacetelescope/jdaviz pull request #1454
Opened 2022-07-05 21:13 UTC by duytnguyendtn

### Description

Enhances one of the display tests from #965 to check for the explicit error, rather than the outer, generic, chained, user-friendly error

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

2022-07-05 21:21 UTC, pllim commented
Is this really what you want? Or you rather raise a straight up `NotImplementedError`?

2022-07-05 21:24 UTC, duytnguyendtn commented
@pllim RE https://github.com/spacetelescope/jdaviz/pull/965#issuecomment-1175501315: I'm actually explicitly trying to wrap all the errors with the RuntimeError. Specifically, I wanted to explicitly wrap all the errors with the RuntimeError message to "tell the story" of why things broke. It's probably obvious for us as SEs when an exception raises when running `show()` that there was an error displaying Jdaviz, but I want to try to help along the super novice by adding some "user friendly padding", which is what that RuntimeError is

2022-07-05 21:25 UTC, duytnguyendtn commented
And FWIW, this isn't really for the NotImplemented Error, this should also be for the ValueError as well for the unrecognized arg

2022-07-05 21:27 UTC, duytnguyendtn commented
So really it should look like https://github.com/spacetelescope/jdaviz/pull/1454/commits/1b8605e32c7f3548f0645ca2c4eab138c6ecfd99

2022-07-05 21:28 UTC, pllim requested changes
I think you can write the rest without try/except like this:

```python
with pytest.raises(RuntimeError, match='Error in displaying Jdaviz') as err:
    ...
assert ....
```

2022-07-05 21:34 UTC, duytnguyendtn commented
So like that https://github.com/spacetelescope/jdaviz/pull/1454/commits/6d84917c4e3255efe0e9de5565e8312416aa2e93?

2022-07-05 22:16 UTC, pllim commented on jdaviz/tests/test_show.py
> +        assert isinstance(err.__cause__, NotImplementedError)
Yes, but let's do that outside of the context manager as pytest recommended in https://docs.pytest.org/en/stable/how-to/assert.html#assertions-about-expected-exceptions 😸 

```suggestion
    assert isinstance(err.__cause__, NotImplementedError)
```

2022-07-05 22:16 UTC, pllim commented on jdaviz/tests/test_show.py
> +        assert isinstance(err.__cause__, ValueError)
```suggestion
    assert isinstance(err.__cause__, ValueError)
```

2022-07-06 13:20 UTC, duytnguyendtn commented
OH lol clearly my C brain was engaged because I was thinking "Oh, if the assert isn't under the context manager, how can it access the exception defined inside?? 😆

2022-07-06 13:24 UTC, pllim approved these changes
LGTM. Thanks!

p.s. Didn't know there is a `__cause__`. TIL!

2022-07-06 13:26 UTC, duytnguyendtn commented
Whoops, something broke.... one sec

2022-07-06 13:28 UTC, pllim commented
Hmm... Might need a slightly different syntax to access the cause since pytest exception object isn't pure Python object. 😬

2022-07-06 13:35 UTC, duytnguyendtn commented
Found it! https://stackoverflow.com/questions/70499076/how-to-check-exception-cause-using-pytest-raises
```
err.value.__cause__
```

2022-07-06 13:37 UTC, duytnguyendtn commented
`trivial` = 1 approval, so I'll merge once the tests pass (though if you catch it before I do, feel free Pey-Lian!)

2022-07-06 13:40 UTC, pllim commented
Please use the "Squash and Merge" button. Thanks!

2022-07-06 13:49 UTC, merged