numpy deprecation warning filter for v1.24.0
spacetelescope/jdaviz pull request #1873
Opened 2022-11-28 15:10 UTC by bmorris3

Numpy v1.24.0 triggers several deprecation warnings in scikit-image. See progress on fixes in scikit-image/scikit-image#6633, and failure in #1834.

This PR tries to filter out that specific deprecation warning.

### Description

This pull request is to address ...

Fixes #<Issue Number>

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

2022-11-28 16:08 UTC, pllim requested changes
Blanket ignore seems overkill for something that only crops up on dev job.

Lemme catch up on the logs and see if we can do something more localized.

2022-11-28 16:16 UTC, bmorris3 commented
@pllim – to help you up to speed, see [this warning](https://github.com/spacetelescope/jdaviz/actions/runs/3550655505/jobs/5964421579#step:5:274), for example.

2022-11-28 19:29 UTC, pllim commented
You might need to fix the regex.

2022-11-28 19:30 UTC, bmorris3 commented
@pllim That's what I was worried about, but couldn't figure out how to test it locally. Trying again.

2022-11-28 19:45 UTC, pllim commented on setup.cfg
> +    ignore:is a deprecated alias for:DeprecationWarning
Maybe a little more specific? 😬 
```suggestion
    ignore:.*np\.bool8.*is a deprecated alias for:DeprecationWarning
```

2022-11-28 20:46 UTC, pllim commented on setup.cfg
> +    ignore:.*np\.unit0.*is a deprecated alias for:DeprecationWarning
What is unit0 ? 
```suggestion
    ignore:.*np\.int0.*is a deprecated alias for:DeprecationWarning
```

2022-11-28 21:41 UTC, bmorris3 commented on setup.cfg
> +    ignore:.*np\.unit0.*is a deprecated alias for:DeprecationWarning
🤦🏻

2022-11-28 22:48 UTC, pllim commented
Maybe it was `int0` and not `uint0` or both?

`DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.`

2022-11-28 22:49 UTC, pllim commented
Also these are strictly upstream right? Do you plan to fix `uint0` and `int0` upstream too?

2022-11-29 14:30 UTC, pllim commented on jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
> +    dec = np.array(footprint[1::2], dtype=np.float_)
Isn't this what numpy actually suggested?

```suggestion
    ra = np.array(footprint[::2], dtype=float)
    dec = np.array(footprint[1::2], dtype=float)
```

2022-11-29 20:06 UTC, pllim commented
Ignore the release job failure. It is https://github.com/pypa/twine/issues/940

2022-11-29 20:35 UTC, pllim commented
Remaining failures in the devdeps job all use https://stsci.box.com/shared/static/exnkul627fcuhy5akf2gswytud5tazmw.fits . Curious that this file worked with the other remote data job but not this one, but investigating it is out of scope here.

2022-11-29 21:17 UTC, pllim approved these changes

2022-11-29 21:18 UTC, merged

2022-11-29 21:20 UTC, pllim commented on jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
> +    dec = np.array(footprint[1::2], dtype=float)
I backported this to v3.1.x in d7ec0ab70c885246be00d8312e7b596b88e286dc