Link Mosviz spectrum viewer x axes
spacetelescope/jdaviz pull request #264
Opened 2020-09-02 20:23 UTC by rosteen

Adds `observe` methods on the x-axes of the Mosviz spectrum viewers to update the other spectrum viewer's x scale when the one is changed.

2020-09-02 21:13 UTC, javerbukh commented
1) When I click the 2nd row, I get an error with a pretty long traceback that ends in
```
~/Documents/jdadf_notebooks/jdaviz/jdaviz/configs/mosviz/helper.py in _update_spec1d_x_axis(self, change)
     50             spec1d = self.app.get_viewer('table-viewer')._selected_data["spectrum-viewer"]
     51             world = self.app.data_collection[spec1d]["World 0"]
---> 52             val = world[new_idx]
     53             scales = self.app.get_viewer('spectrum-viewer').scales
     54             old_val = getattr(scales['x'], name)

IndexError: index 1432 is out of bounds for axis 0 with size 1351
```

2) When I click PanZoom on the 2d spectra and drag, it seems like the 1d spectra is being stretched out (meaning the right side is anchored while the left side moves off screen, kind of like it is being zoomed rather than panned) rather than moving in the same way the 2d spectra is. Same behavior happens when I PanZoom the 1d spectra.

3) It seems like using the "PanZoom in the x direction" button in the 1d spectrum viewer works, however.

2020-09-02 22:29 UTC, dtn5ah approved these changes
Surprisingly performant! I was so sure this was going to add to our existing performance issues :P

2020-09-02 22:43 UTC, dtn5ah commented
I think I found the impodus to @javerbukh's bug. When I click the second item, sometimes (it's sporadic though...) it looks like the viewers aren't updating properly; the 2D spectra viewer is completely blank:
![image](https://user-images.githubusercontent.com/25206008/92044228-bf895500-ed4b-11ea-80ae-9b01c93146ac.png)
Interestingly, this is despite the correct 2D spectra being selected:
![image](https://user-images.githubusercontent.com/25206008/92044337-0b3bfe80-ed4c-11ea-8e1b-3e20318920ec.png)
The reason I think the viewers are getting out of sync because the 1D spectra is interestingly still on index 0:
![image](https://user-images.githubusercontent.com/25206008/92044397-29096380-ed4c-11ea-9358-7b4d0314f266.png)

2020-09-03 13:42 UTC, rosteen commented
@dtn5ah I was honestly surprised by the performance as well, I expected to have to work to try to get it to be faster but it worked well right off the bat.

All of the errors are, I think, because I didn't consider handling the case where the user pans past the bounds of the data. So the "closest array index" is always giving the last index for the 2D spectrum (if you pan the 1D too far) or throwing an error trying to get the wavelength at an index of the 1D spectrum that doesn't exist (if you pan the 2D too far). I could either extrapolate, or lock the edges if there isn't much of a use case for panning past the bounds of the data - I'll see what POs think at the tagup today. 

Pretty sure the case of the second row failing is related to the edge problem, because of a size mismatch between the arrays associated with the rows. Thanks for pointing these out, I'll have some updates later today.

2020-09-03 17:56 UTC, rosteen commented
@javerbukh @dtn5ah  Now lets you pan past the bounds of the data for a bit before the stretching behavior shows up. If you've gone that far, well...just go back there's no data out there why are you still trying to pan that way?!

2020-09-03 22:36 UTC, dtn5ah requested changes
Dragging along the 1D spectra works like expected. However when I drag the 2D spectra, I still get @javerbukh's bug to happen.

Also, even in the 1D spectra, when you drag "too far" to either side, the spectra appears to "snap" to a blank part of the range until you drag back to the spectral bounds. Is this the behavior we're trying to go for? I'd imagine that it should just stop in the last bit of spectra?

2020-09-04 13:37 UTC, rosteen commented
@dtn5ah you should now be able to pan all the way to not having any data in the viewer before getting any errors. I also added the x-only pan/zoom tool to the 2D spectrum viewer's toolbar, since it seems to make sense there.

2020-09-04 14:23 UTC, javerbukh approved these changes
Still seeing this error when panning past where the data is
`IndexError: index 3497 is out of bounds for axis 0 with size 3456`
but I agree that there is no reason a user should be going that far. I would suggest some sort of check to prevent the error from popping up, but otherwise this looks and works great!

2020-09-04 14:26 UTC, rosteen commented
I think I'll add a snackbar message warning that the viewers are no longer in sync at that point, which will avoid throwing a bunch of errors in the error log. Didn't quite have time to add that before our tagup, since I was trying to get a similar fix in for the model fitting.

2020-09-04 18:54 UTC, dtn5ah approved these changes
Yay no ugly tracebacks! Snackbar warning works as expected

2020-09-04 18:56 UTC, merged