Jdaviz doc
spacetelescope/jdaviz pull request #269
Opened 2020-09-05 15:34 UTC by PatrickOgle

Documentation for Cubeviz plugins

2020-09-08 13:50 UTC, rosteen requested changes
One minor suggestion, other than that it looks good. I think I'll plan to make a follow-up PR that enables the `autosectionlabel` sphinx plugin so that the references to the Specviz doc pages in the text can also be links.

2020-09-08 13:50 UTC, rosteen commented on docs/cubeviz/plugins.rst
> +also saved to a 'Model' dataset.
```suggestion
also saved to a dataset with the label specified in the :guilabel:`Model Label` field (default 'Model').
```

2020-09-10 14:02 UTC, javerbukh approved these changes
Looks good, nice work! I think once glue-jupyter has the contours in we can quickly throw in some information about how to use that, but that can be after this is merged.

2020-09-10 14:03 UTC, rosteen approved these changes

2020-09-10 14:04 UTC, javerbukh commented
LGTM!

2020-09-10 14:05 UTC, merged