Updated index.rst file
spacetelescope/jdaviz pull request #308
Opened 2020-09-23 16:24 UTC by orifox

Removed Collapsing Cubes and made link to JDox.

2020-09-23 16:35 UTC, javerbukh commented
Is there a reason you deleted the `quickstart.rst` file and the collapsing cubes file?

2020-09-25 18:52 UTC, orifox commented
Jesse, first one was a typo (quickstart.rst) is supposed to still be there.  Thanks.  Second one was intentional.  I though we were moving collapsing cubes into the plugins section.  See outline here: https://innerspace.stsci.edu/display/DATB/Outline+of+jdaviz+documentation

2020-09-30 14:31 UTC, javerbukh commented
I understand the motivation behind linking to https://jwst-docs.stsci.edu/jwst-post-pipeline-data-analysis, however, that page links to the old (QT) versions of specviz, mosviz, and cubebviz. Once that page is updated to link to the jdaviz repo, I think we can merge this PR. As it stands, I think this will add confusion to people reading through the documentation thoroughly.

2020-10-01 13:24 UTC, orifox commented
Ok, the JDox page is updated!  Please take a look and merge :)

2020-10-02 21:23 UTC, javerbukh commented on README.rst
>  tools based on the Jupyter platform.  These GUI-based tools link data
```suggestion
``jdaviz`` is a package of astronomical data analysis visualization tools based on the Jupyter platform. It is one tool that is a part of STScI's larger `Data Analysis Tools Ecosystem <https://jwst-docs.stsci.edu/jwst-post-pipeline-data-analysis>`_. These GUI-based tools link data
```

2020-10-02 21:24 UTC, javerbukh requested changes
Left a comment. I think the change to the RTD index page is good but the change to the README file do not appear as expected. My suggestions remove the `.. note::` line since that is a Sphinx tool reference to the documentation, which the user can access by clicking the badge already in the README.

2020-10-04 20:18 UTC, orifox commented
Ok, thanks. I was hoping that would get caught in the review process.  Perfect.  Thanks for the change.

2020-10-05 20:05 UTC, javerbukh approved these changes
Looks good to me!

2020-10-06 13:12 UTC, merged