add specviz property to cubeviz/mosviz helpers
spacetelescope/jdaviz pull request #330
Opened 2020-10-08 17:32 UTC by eteq

This implements the feature I suggested in #329. This PR should probably also include some doc updates showing its use a la what @PatrickOgle originally was thinking about in https://github.com/spacetelescope/jdaviz/pull/257#discussion_r483014900.  The idea is that with this you can do something like:
```
cubeviz = CubeViz()
cubeviz.load_data(...)

cubeviz.specviz.some_specviz_helper(...)
```
and that should be documented as the intended approach to using specviz helpers in the cubeviz context.

2020-11-02 19:53 UTC, eteq commented
After some out-of-band discussion w/ @javerbukh @dtn5ah @rosteen @havok2063 , there's some agreement that this is the way we want to go as an idiom for connecting together "sub-vizes".  So I'm converting to "regular" PR.

2021-02-05 21:07 UTC, rosteen requested changes
We definitely should make a note of this in the docs, and probably add a test for Mosviz and Cubeviz to check that it works (maybe just a call to e.g. `viz.specviz.get_spectra()` or something). Do you have bandwidth to make those additions @eteq or should someone else take over?

2021-02-05 21:52 UTC, eteq commented
Hmm.  I *think* I have time, but I have said that before and been wrong.  Maybe give it another several days, @rosteen, and if I haven't gotten to it by then someone else should jump in?

2021-02-09 14:34 UTC, ibusko approved these changes
I tested the basic loading sequence and it works. LGTM

2021-04-12 13:46 UTC, rosteen approved these changes
Approving this, I have a couple docs additions that I'll put in a follow-up PR shortly, rather than adding them here. I'll resolve the merge conflicts here.

2021-04-12 14:47 UTC, rosteen reviewed
Suggested two blank line addition/deletions to fix codestyle errors.

2021-04-12 14:47 UTC, rosteen commented on jdaviz/configs/cubeviz/helper.py
```suggestion


```

2021-04-12 14:47 UTC, rosteen commented on jdaviz/configs/mosviz/helper.py
> +
```suggestion
```

2021-04-12 15:21 UTC, merged