Updated Cubeviz Displaying Spectra
spacetelescope/jdaviz pull request #346
Opened 2020-10-19 16:02 UTC by PatrickOgle

Added documentation to Cubeviz:Displaying Spectra

2020-10-19 17:42 UTC, rosteen requested changes
The text in the `seealso` link didn't seem to match the linked page, so I made a couple suggestions.

2020-10-19 17:42 UTC, rosteen commented on docs/cubeviz/displayspectra.rst
> +    `Gaussian Smooth <https://jdaviz.readthedocs.io/en/latest/specviz/displaying.html`_
```suggestion
    `Displaying Spectra (Specviz) <https://jdaviz.readthedocs.io/en/latest/specviz/displaying.html>`_
```
Fix missing close bracket, change the text to match the linked page.

2020-10-19 17:42 UTC, rosteen commented on docs/cubeviz/displayspectra.rst
> +        Specviz documentation on gaussian smoothing of 1D spectra.
```suggestion
        Specviz documentation on displaying 1D spectra.
```

2020-10-19 17:51 UTC, PatrickOgle commented on docs/cubeviz/displayspectra.rst
> +        Specviz documentation on gaussian smoothing of 1D spectra.
```suggestion
        Documentation on displaying spectra in a 1D spectrum viewer.
```

2020-10-19 17:54 UTC, rosteen approved these changes

2020-10-20 13:52 UTC, PatrickOgle commented on docs/cubeviz/displayspectra.rst
> +below.
```suggestion
below. 
```

2020-10-20 16:03 UTC, javerbukh approved these changes
Looks good!

2020-10-20 16:03 UTC, javerbukh commented
Merging.

2020-10-20 16:04 UTC, merged