Extract Mosviz table with to_csv method
spacetelescope/jdaviz pull request #468
Opened 2021-03-15 19:15 UTC by rosteen

What it says in the title. Takes `filename` (string) and `selected` (boolean, default False) optional inputs.

2021-03-15 20:17 UTC, javerbukh approved these changes
Looks good! I wasn't sure if @camipacifici wanted some way to print things to a notebook cell in addition to this functionality but as far as providing a `.csv` export this checks that box!

2021-03-15 20:20 UTC, rosteen commented
There's already a `mosviz.to_table()` method that returns an astropy table, although I haven't tested/used it so perhaps it needs to be updated/improved.

2021-03-15 20:23 UTC, javerbukh commented
The `to_table()` method does not seem to be working currently.

2021-03-15 20:25 UTC, rosteen commented
Well $^&% to that. I guess I should probably fix it, and make sure what it returns is consistent with `to_csv`.

2021-03-16 02:21 UTC, camipacifici reviewed
Looks good.
`to_csv()` works as expected.

I confirm that `to_table()` does not work.

Traceback:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-03c6e3ef8526> in <module>
----> 1 mosviz.to_table()

~/Documents/JDAT/jdaviz_bug_fixes/jdaviz/jdaviz/configs/mosviz/helper.py in to_table(self)
    235             unit = u.Unit(comp.units)
    236 
--> 237             data_dict[cid.label] = comp.data * unit
    238 
    239         return QTable(data_dict)

TypeError: unsupported operand type(s) for *: 'categorical_ndarray' and 'CompositeUnit'

2021-03-16 14:27 UTC, rosteen commented
I fixed `to_table`, it was breaking when the columns had no associated units, as would be expected for the columns with source names or other strings. However, it also appears that there are no units associated with the RA and DEC columns, which surprised me. I'll create an issue to look into that.

2021-03-16 18:52 UTC, duytnguyendtn requested changes
Functionally, looks good, but I do have one concern: When a csv already exists, the default behavior is to clobber the old file and replace it with a new one. I'm generally nervous when software destroys artifacts without explicit approval. I would suggest the following behavior:
1. Default: Check if the file already exists. If it doesn't, go ahead. If it does, throw a `FileExistsError`. 
2. Add an `overwrite=True` flag that silently overwrites the file without any confirmation

2021-03-16 20:44 UTC, rosteen commented
Good suggestion @duytnguyendtn , implemented.

2021-03-16 21:02 UTC, duytnguyendtn approved these changes
Awesome, thanks for the implement!

2021-03-16 21:02 UTC, duytnguyendtn commented
2 reviews = acceptance criteria met, merging!

2021-03-16 21:02 UTC, merged