MNT: Rebrand SomeViz to Someviz
spacetelescope/jdaviz pull request #856
Opened 2021-09-10 14:07 UTC by pllim

### Description

This pull request is to apply consistent branding across the package. I think this is pretty important to get done early on before we have hundreds notebooks in the wild with old branding.

Fixes #178

TODO:

- [ ] Rebrand other viz.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

2021-09-10 16:35 UTC, pllim commented on jdaviz/configs/cubeviz/plugins/viewers.py
> +class CubeVizImageView(CubevizImageView):
Actually, I am not sure if this trick would work here given the `@viewer_registry` usage.

If the user does not call this class directly, maybe we can just rename without any backward compatibility?

2021-09-10 16:57 UTC, pllim commented
@havok2063 , you should see how much this affects MAST stuff.

2021-09-10 17:25 UTC, havok2063 commented
@plim oh it does!  this directly impacts MAST.  I would want to try and coordinate when and if this gets merged, if this is included in the tag for the MAST freeze, and if this change is enough to get approval for an update to our OPs environment

2021-09-10 17:26 UTC, pllim commented
> this directly impacts MAST

Even with my attempt at backward compatibility?

2021-09-10 17:27 UTC, pllim commented
I am hoping this would go in for the upcoming release. Otherwise, renaming will just get more painful if we wait longer.

2021-09-10 17:28 UTC, havok2063 commented
Keeping the deprecated classes around for a bit definitely helps, and gives us a little wiggle room, regarding deployments.

2021-09-10 17:31 UTC, pllim commented
The only thing I cannot really keep is the old _viewer_ classes. I don't think I can register both old and new classes to the same viewer registry. So unless you are calling low level viz stuff directly, I am hoping the impact here is minimal for you. Did you look at the diff?

2021-09-13 14:03 UTC, havok2063 commented
I had a quick skim through the diff.  We don't use any lower level access at the moment.  Only main class imports, i.e.
```
from jdaviz.app import Application
from jdaviz.core.config import get_configuration
from jdaviz.core.data_formats import get_valid_format
from jdaviz import SpecViz, CubeViz, Specviz2d
```
and accessing the viewer names as written in the `configs` directory to retrieve a viewer's settings.  So as long as the old class names are around for it, I think MAST will continue to work.  But I could a quick test to make sure whenever this is ready to be merged.

2021-09-13 14:04 UTC, pllim commented
> But I could a quick test to make sure whenever this is ready to be merged.

I would merge it today if others let me. I think this is important for the upcoming release if we are going to rebrand stuff.

2021-09-13 16:49 UTC, havok2063 commented
Just tested this.  In order for MAST to continue working in the short term with this PR without changes, we need the deprecated classes available at the top level, i.e. `from jdaviz import SpecViz, CubeViz, Specviz2d`.  Right now they are no longer available.  I think simply adding the old class in each helper init should resolve this.  E.g. in `configs/specviz/__init__.py` modify `from .helper import Specviz` to `from .helper import Specviz, SpecViz`

2021-09-13 16:59 UTC, havok2063 requested changes
See previous comment regarding solution to allow MAST to continue to use this without changes, until we can determine when we can fold these changes into our code.

2021-09-13 16:59 UTC, havok2063 commented on jdaviz/__init__.py
> +from jdaviz.configs.specviz import Specviz  # noqa
```suggestion
from jdaviz.configs.specviz import Specviz, SpecViz  # noqa
```

2021-09-13 16:59 UTC, havok2063 commented on jdaviz/__init__.py
> +from jdaviz.configs.mosviz import Mosviz  # noqa
```suggestion
from jdaviz.configs.mosviz import Mosviz, MosViz  # noqa
```

2021-09-13 16:59 UTC, havok2063 commented on jdaviz/__init__.py
> +from jdaviz.configs.cubeviz import Cubeviz  # noqa
```suggestion
from jdaviz.configs.cubeviz import Cubeviz, CubeViz  # noqa
```

2021-09-13 16:59 UTC, havok2063 commented on jdaviz/configs/cubeviz/__init__.py
> +from .helper import Cubeviz  # noqa
```suggestion
from .helper import Cubeviz, CubeViz  # noqa
```

2021-09-13 16:59 UTC, havok2063 commented on jdaviz/configs/mosviz/__init__.py
> +from .helper import Mosviz  # noqa
```suggestion
from .helper import Mosviz, MosViz  # noqa
```

2021-09-13 16:59 UTC, havok2063 commented on jdaviz/configs/specviz/__init__.py
> +from .helper import Specviz  # noqa
```suggestion
from .helper import Specviz, SpecViz  # noqa
```

2021-09-13 17:14 UTC, havok2063 commented
Tested and works!

2021-09-13 17:16 UTC, pllim commented
@havok2063 , please approve if you are happy. Thanks for the review! 😸

2021-09-13 17:17 UTC, havok2063 approved these changes

2021-09-13 18:41 UTC, rosteen approved these changes
Awesome, this is way overdue. Thanks!

2021-09-13 18:41 UTC, merged